version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    restart: on-failure
    build: ./
    container_name: api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  data-db:
